# Generated by Django 6.0.4 on 2026-05-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_message_sfx_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='group_image',
            field=models.ImageField(blank=True, null=True, upload_to='group_headers/'),
        ),
    ]
