# Generated by Django 6.0.4 on 2026-05-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_story_group_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='elevenlabs_voice_id',
            field=models.CharField(default='pNInz6obpgDQGcFmaJgB', help_text='ElevenLabs Voice ID', max_length=50),
        ),
        migrations.AddField(
            model_name='message',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='messages_audio/'),
        ),
    ]
